version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14

    volumes:
        - ..:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - car-collector-network
    # Runs app on the same network as the s3
    # network_mode: service:s3


  s3:
    image: minio/minio:edge
    ports:
        - '9000:9000'
    command: server /home/s3
    networks:
        - car-collector-network
    environment:
        - MINIO_ACCESS_KEY=test
        - MINIO_SECRET_KEY=testtest
    volumes:
        - ./data/s3:/home/s3/
  # This service creates an image bucket in the local minio for development 
  # Since the `depends_on` isn't enough to wait for the minio service to be
  # completely up, the entrypoint repeatedly tries to connect
  car-collector-bucket:
    image: minio/mc
    depends_on:
        - s3
    networks:
        - car-collector-network
    entrypoint: >
        /bin/sh -c "
        until /usr/bin/mc config host add s3 http://s3:9000 test testtest;
        do echo 'Minio is unavailable - sleeping'; 
        sleep 1; 
        done;
        /usr/bin/mc mb s3/test-cars;
        /usr/bin/mc policy set download s3/test-cars;
        exit 0;
        "

networks:
    car-collector-network:
