app: data-collector
service: car-collector
disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_S3_REGION}
  stackTags:
    Owner: Olli Saarinen
    Project: car-collector-${opt:stage}
  environment:
    AWS_S3_URL: !Join ['', ['https://', Fn::GetAtt [CarBucket, DomainName]]]
    AWS_S3_ACCESS_KEY: !Ref S3UserAccessKey
    AWS_S3_ACCESS_SECRET: Fn::GetAtt ["S3UserAccessKey", "SecretAccessKey"]
    AWS_S3_CAR_BUCKET: !Ref CarBucket
  iamrolestatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: CarBucket
            - '/*'
package:
  exclude:
    - .env.local

functions:
  new-cars:
    handler: app/handler.saveNewCars
    events:
      - schedule:
          rate: cron(0 4 * * ? *)
          enabled: false

custom:
  # Local development
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

resources:
  Conditions:
    IsProd: !Equals ["${opt:stage}", "prod"]
  Resources:
    CarBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${opt:stage}-car-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
    S3User:
      Type: AWS::IAM::User
      Properties:
        Policies:
          - PolicyName: bucket-access
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${CarBucket}
                  - !Sub arn:aws:s3:::${CarBucket}/*
    S3UserAccessKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName: !Ref S3User
    