app: data-collector
service: car-collector

useDotenv: false
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    HELLO: admin
    MOI: ${env:MOI}

functions:
  hello:
    handler: app/handler.hello
    events:
      - http:
          path: /hello
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
