app: data-collector
service: car-collector
disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs14.x

functions:
  new-cars:
    handler: app/handler.saveNewCars
    events:
      - schedule:
          rate: cron(0 4 * * ? *)
          enabled: false

custom:
  # Local development
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
