app: data-collector
service: car-collector
disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: app/handler.hello
    events:
      - http:
          path: /hello
          method: get
  new-cars:
    handler: app/handler.saveNewCars
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: false
  buckets:
    handler: app/handler.getBuckets
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: false

custom:
  # Local development
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
