app: data-collector
service: car-collector

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    HELLO: admin
    MOI: ${env:AWS_S3_CAR_BUCKET}

functions:
  hello:
    handler: app/handler.hello
    events:
      - http:
          path: /hello
          method: get
  timed-hello:
    handler: app/handler.getCars
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: false
  get-s3:
    handler: app/handler.getBucket
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: false

custom:
  # Local development
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
