app: data-collector
service: car-collector
disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_S3_REGION}
  stackTags:
    Owner: Olli Saarinen
    Project: car-collector-${opt:stage}
  environment:
    AWS_S3_URL: !Join ['', ['https://', !GetAtt ["CarBucket", "DomainName"]]]
    AWS_S3_ACCESS_KEY: !Ref S3UserAccessKey
    AWS_S3_ACCESS_SECRET: !GetAtt ["S3UserAccessKey", "SecretAccessKey"]
    AWS_S3_CAR_BUCKET: !Ref CarBucket
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: CarBucket
                - '/*'
package:
  exclude:
    - .env.dev

functions:
  new-cars:
    handler: app/handler.saveNewCars
    timeout: 500
    events:
      - schedule:
          rate: cron(59 23 * * ? *)
          enabled: true

custom:
  # Local development
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

resources:

  Conditions:
    IsProd: !Equals ["${opt:stage}", "prod"]

  Resources:
    CarBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${opt:stage}-car-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True

    S3User:
      Type: AWS::IAM::User
      Properties:
        Policies:
          - PolicyName: bucket-access
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${CarBucket}
                  - !Sub arn:aws:s3:::${CarBucket}/*

    S3UserAccessKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName: !Ref S3User

    CarGlueDatabase:
      Type: AWS::Glue::Database
      Properties: 
        CatalogId: !Ref AWS::AccountId
        DatabaseInput: 
            Description: Car Collector Database
            Name: carcollector

    CarGlueTable:
      Type: AWS::Glue::Table
      Properties: 
        CatalogId: !Ref AWS::AccountId
        DatabaseName: !Ref CarGlueDatabase
        TableInput: 
          Description: Cars from Nettiauto
          Name: cars
          TableType: EXTERNAL_TABLE
          Parameters: { EXTERNAL: TRUE, has_encrypted_data: false, classification: json }
          PartitionKeys: 
            - Name: year
              Type: int
            - Name: week
              Type: int
          StorageDescriptor:
              InputFormat: org.apache.hadoop.mapred.TextInputFormat
              OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
              SerdeInfo:
                SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
                Parameters: { serialization.format: 1 }
              Location: !Sub s3://${CarBucket}/
              StoredAsSubDirectories: False
              Columns: 
                - Name: id
                  Type: string
                - Name: adurl
                  Type: string
                - Name: username
                  Type: string
                - Name: datecreated
                  Type: timestamp
                - Name: dateupdated
                  Type: timestamp
                - Name: vehicletype
                  Type: string
                - Name: bodytype
                  Type: string
                - Name: fueltype
                  Type: string
                - Name: geartype
                  Type: string
                - Name: region
                  Type: string
                - Name: manufacturingyear
                  Type: int
                - Name: firstregistrationyear
                  Type: int
                - Name: price
                  Type: int
                - Name: registernumber
                  Type: string
                - Name: consumptioncombined
                  Type: double
                - Name: enginesize
                  Type: double
                - Name: kilometers
                  Type: bigint
    