app: data-collector
service: car-collector
disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_S3_REGION}
  stackTags:
    Owner: Olli Saarinen
    Project: car-collector-${opt:stage}

  iamrolestatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: CarBucket
            - '/*'

functions:
  new-cars:
    handler: app/handler.saveNewCars
    events:
      - schedule:
          rate: cron(0 4 * * ? *)
          enabled: false

custom:
  # Local development
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

resources:
  Conditions:
    IsProd: !Equals ["${opt:stage}", "prod"]
  Resources:
    CarBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${opt:stage}-car-bucket
  