# Car collector CI/CD workflow, triggered form car-collector folder
name: Car Collector CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'car-collector/**'
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: car-collector

jobs:
  # Build etc other PR feedbacks.
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install deps
      run: npm ci
      
    - name: Run build
      run: npm run build
      
    - name: Run lint
      run: npm run lint
      
    - name: Run unit tests
      run: npm test

  # Deployment (non PR)
  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    # environment:
    #   name: PROD
    #   url: ${{ steps.deploywebapp.outputs.webapp-url }}
    steps:
      - run: echo "Not A PR"
